// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module keccak_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic
) (
  input clk_i,
  input rst_ni,

  // Below Register interface can be changed
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output keccak_reg_pkg::keccak_reg2hw_t reg2hw, // Write
  input  keccak_reg_pkg::keccak_hw2reg_t hw2reg, // Read

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import keccak_reg_pkg::* ;

  localparam int AW = 5;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;

  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;

  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err ;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] din_0_wd;
  logic din_0_we;
  logic [31:0] din_1_wd;
  logic din_1_we;
  logic [31:0] dout_0_qs;
  logic dout_0_re;
  logic [31:0] dout_1_qs;
  logic dout_1_re;
  logic ctrl1_start_qs;
  logic ctrl1_start_wd;
  logic ctrl1_start_we;
  logic ctrl1_start_re;
  logic ctrl1_din_valid_qs;
  logic ctrl1_din_valid_wd;
  logic ctrl1_din_valid_we;
  logic ctrl1_din_valid_re;
  logic ctrl1_last_block_qs;
  logic ctrl1_last_block_wd;
  logic ctrl1_last_block_we;
  logic ctrl1_last_block_re;
  logic status_dout_valid_qs;
  logic status_dout_valid_re;
  logic status_buffer_full_qs;
  logic status_buffer_full_re;
  logic status_ready_qs;
  logic status_ready_re;

  // Register instances

  // Subregister 0 of Multireg din
  // R[din_0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("WO"),
    .RESVAL  (32'h0)
  ) u_din_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (din_0_we),
    .wd     (din_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.din[0].q ),

    .qs     ()
  );

  // Subregister 1 of Multireg din
  // R[din_1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("WO"),
    .RESVAL  (32'h0)
  ) u_din_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (din_1_we),
    .wd     (din_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.din[1].q ),

    .qs     ()
  );



  // Subregister 0 of Multireg dout
  // R[dout_0]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_dout_0 (
    .re     (dout_0_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.dout[0].d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (dout_0_qs)
  );

  // Subregister 1 of Multireg dout
  // R[dout_1]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_dout_1 (
    .re     (dout_1_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.dout[1].d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (dout_1_qs)
  );


  // R[ctrl1]: V(True)

  //   F[start]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl1_start (
    .re     (ctrl1_start_re),
    .we     (ctrl1_start_we),
    .wd     (ctrl1_start_wd),
    .d      (hw2reg.ctrl1.start.d),
    .qre    (),
    .qe     (reg2hw.ctrl1.start.qe),
    .q      (reg2hw.ctrl1.start.q ),
    .qs     (ctrl1_start_qs)
  );


  //   F[din_valid]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl1_din_valid (
    .re     (ctrl1_din_valid_re),
    .we     (ctrl1_din_valid_we),
    .wd     (ctrl1_din_valid_wd),
    .d      (hw2reg.ctrl1.din_valid.d),
    .qre    (),
    .qe     (reg2hw.ctrl1.din_valid.qe),
    .q      (reg2hw.ctrl1.din_valid.q ),
    .qs     (ctrl1_din_valid_qs)
  );


  //   F[last_block]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl1_last_block (
    .re     (ctrl1_last_block_re),
    .we     (ctrl1_last_block_we),
    .wd     (ctrl1_last_block_wd),
    .d      (hw2reg.ctrl1.last_block.d),
    .qre    (),
    .qe     (reg2hw.ctrl1.last_block.qe),
    .q      (reg2hw.ctrl1.last_block.q ),
    .qs     (ctrl1_last_block_qs)
  );


  // R[status]: V(True)

  //   F[dout_valid]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_dout_valid (
    .re     (status_dout_valid_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.dout_valid.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_dout_valid_qs)
  );


  //   F[buffer_full]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_buffer_full (
    .re     (status_buffer_full_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.buffer_full.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_buffer_full_qs)
  );


  //   F[ready]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_ready (
    .re     (status_ready_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.ready.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_ready_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == KECCAK_DIN_0_OFFSET);
    addr_hit[1] = (reg_addr == KECCAK_DIN_1_OFFSET);
    addr_hit[2] = (reg_addr == KECCAK_DOUT_0_OFFSET);
    addr_hit[3] = (reg_addr == KECCAK_DOUT_1_OFFSET);
    addr_hit[4] = (reg_addr == KECCAK_CTRL1_OFFSET);
    addr_hit[5] = (reg_addr == KECCAK_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = 1'b0;
    if (addr_hit[0] && reg_we && (KECCAK_PERMIT[0] != (KECCAK_PERMIT[0] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[1] && reg_we && (KECCAK_PERMIT[1] != (KECCAK_PERMIT[1] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[2] && reg_we && (KECCAK_PERMIT[2] != (KECCAK_PERMIT[2] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[3] && reg_we && (KECCAK_PERMIT[3] != (KECCAK_PERMIT[3] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[4] && reg_we && (KECCAK_PERMIT[4] != (KECCAK_PERMIT[4] & reg_be))) wr_err = 1'b1 ;
    if (addr_hit[5] && reg_we && (KECCAK_PERMIT[5] != (KECCAK_PERMIT[5] & reg_be))) wr_err = 1'b1 ;
  end

  assign din_0_we = addr_hit[0] & reg_we & ~wr_err;
  assign din_0_wd = reg_wdata[31:0];

  assign din_1_we = addr_hit[1] & reg_we & ~wr_err;
  assign din_1_wd = reg_wdata[31:0];

  assign dout_0_re = addr_hit[2] && reg_re;

  assign dout_1_re = addr_hit[3] && reg_re;

  assign ctrl1_start_we = addr_hit[4] & reg_we & ~wr_err;
  assign ctrl1_start_wd = reg_wdata[0];
  assign ctrl1_start_re = addr_hit[4] && reg_re;

  assign ctrl1_din_valid_we = addr_hit[4] & reg_we & ~wr_err;
  assign ctrl1_din_valid_wd = reg_wdata[1];
  assign ctrl1_din_valid_re = addr_hit[4] && reg_re;

  assign ctrl1_last_block_we = addr_hit[4] & reg_we & ~wr_err;
  assign ctrl1_last_block_wd = reg_wdata[2];
  assign ctrl1_last_block_re = addr_hit[4] && reg_re;

  assign status_dout_valid_re = addr_hit[5] && reg_re;

  assign status_buffer_full_re = addr_hit[5] && reg_re;

  assign status_ready_re = addr_hit[5] && reg_re;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = dout_0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = dout_1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = ctrl1_start_qs;
        reg_rdata_next[1] = ctrl1_din_valid_qs;
        reg_rdata_next[2] = ctrl1_last_block_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = status_dout_valid_qs;
        reg_rdata_next[1] = status_buffer_full_qs;
        reg_rdata_next[2] = status_ready_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Assertions for Register Interface

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))


endmodule
